name: Update Homebrew formula when new releases are created

on:
  release:
    types:
      - published

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update forumla file
        run: |
          # Get the tag version (e.g., "v1.2.3") from the environment
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')

          git checkout main

          url="https://github.com/PRX/homebrew-dev-tools/archive/refs/tags/$tag.tar.gz"
          wget -O archive "$url"
          chk=$(sha256sum archive | awk '{print $1}')
          rm archive

          # Update the forumla file with the new tag and hash
          sed -i "s/tags\/.*\.tar\.gz/tags\/$tag\.tar\.gz/" Formula/prx-dev-tools.rb
          sed -i "s/sha256.*$/sha256 \"$chk\"/" Formula/prx-dev-tools.rb

          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff
          git add .
          git commit -m "Automatically update formula for release $tag"
          git push
