name: Start CD pipeline execution

on:
  release:
    types:
      - published
  push:
    paths:
      - .github/workflows/update-formula-on-release.yml

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update forumla file
        run: |
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          sed -i -e 's/tags\/.+\.tar\.gz/tags\/'"$tag"'\.tag\.gz/' Formula/prx-dev-tools.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff
# git add .
# git commit -m "generated"
# git push
